core_dashboard_common_app/views/common/forms.py
"""
Common Forms
"""
from django import forms

from core_main_app.components.user import api as user_api


class ActionForm(forms.Form):
    """
    Form to select the action in the user dashboard.
    """

    actions = forms.ChoiceField(label="", required=True, choices=[])

    def __init__(self, list_actions):
        super().__init__()
        self.fields["actions"].choices = list_actions


class UserForm(forms.Form):
    """
    Form to select a user.
    """

    users = forms.ChoiceField(label="", required=True)
    user_options = []

    def __init__(self, current_user):
        self.user_options = []
        self.user_options.append(("", "-----------"))

        # We retrieve all users
        sort_users = user_api.get_active_users()
        # We sort by username, case insensitive
        sort_users = sorted(sort_users, key=lambda s: s.username.lower())

        # We add them
        for user in sort_users:
            if user.id != current_user.id or current_user.is_superuser:
                self.user_options.append((user.id, user.username))

        super().__init__()
        self.fields["users"].choices = []
        self.fields["users"].choices = self.user_options

core_dashboard_common_app/templates/core_dashboard_common_app/home.html
{% load static %}

{% block title %}
<h1><span>Dashboard Home</span></h1>
{% endblock %}

{% block content%}
{% endblock %}

core_dashboard_common_app/templates/core_dashboard_common_app/my_dashboard.html
{% extends 'core_main_app/_render/admin/theme/tools/box.html' %}
{% load special_plural %}

{% block box_title %}
        {% if data.title %}
            <h1>{{data.title}}</h1>
        {% else %}
            {% if come_from_admin %} {{ data.document|special_plural|capfirst}} list {% else %} My {{data.document|special_plural}} {% endif %}
        {% endif %}
{% endblock %}


{% block box_tools %}
    {% if data.create_workspace %}
    <a class="btn btn-secondary create-workspace-btn">
        <i class="fas fa-file-alt"></i> Create workspace
    </a>
    {% endif %}

    {% if data.title %}
        <a href="#" class="btn btn-secondary back-to-previous">
             <i class="fas fa-arrow-left"></i> Previous page
        </a>
    {% endif %}
{% endblock %}


{% block box_body %}
{% if data.user_data %}
    Total number of {{data.document|special_plural}}: {{ data.number_total }}
{% endif %}

{% if data.menu and not data.title %}
<div class="dropdown" id="id_actions" style="display:none">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" {% if BOOTSTRAP_VERSION|first == "4" %}data-toggle{% elif BOOTSTRAP_VERSION|first == "5"  %}data-bs-toggle{% endif %}="dropdown" aria-haspopup="true" aria-expanded="true">
        Choose action
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        {% for value, text in data.action_form.fields.actions.choices %}
            <li style="cursor:  pointer;" onclick="action_dashboard({{value}});">{{text}}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<div class="tab-content">
    {% include data.template with objects=data.user_data group='user' count=data.number_total tabs=data.tabs document=data.document%}
</div>
{% endblock %}

core_dashboard_common_app/templates/core_dashboard_common_app/my_profile.html
{% block title %}
<h2>My Profile</h2>
{% endblock %}

{% block content%}
<div class="btn-group {% if BOOTSTRAP_VERSION|first == "4" %}float-right{% elif BOOTSTRAP_VERSION|first == "5" %}float-end{% endif %}">
	<a class="btn btn-secondary" onclick=" href='{% url 'core_main_set_timezone' %}'">
        <i class="fas fa-globe"></i> Preferences
    </a>
    <a class="btn btn-secondary" onclick=" href='{% url 'core_dashboard_profile_edit' %}'">
        <i class="fas fa-edit"></i> Edit Profile
    </a>
    {% if not data.ENABLE_SAML2_SSO_AUTH %}
	<a class="btn btn-secondary" onclick=" href='{% url 'password_change' %}'">
        <i class="fas fa-lock"></i> Change Password
    </a>
    {% endif %}
</div>
<br/><br/>
<div>
    <table class="table table-bordered table-striped table-hover">
        <tr>
            <td><b>Name:</b></td>
            <td>{{ user.first_name }} {{ user.last_name }}</td>
        </tr>
        <tr>
            <td><b>Username:</b></td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td><b>Email:</b></td>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <td><b>Admin:</b></td>
            <td>{{ user.is_staff }}</td>
        </tr>
        <tr>
            <td><b>Active:</b></td>
            <td>{{ user.is_active }}</td>
        </tr>
        <tr>
            <td><b>Superuser:</b></td>
            <td>{{ user.is_superuser }}</td>
        </tr>
        <tr>
            <td><b>Last Login:</b></td>
            <td>{{ user.last_login }}</td>
        </tr>
        <tr>
            <td><b>Date Joined:</b></td>
            <td>{{ user.date_joined }}</td>
        </tr>
    </table>
</div>
{% endblock %}

core_dashboard_common_app/templates/core_dashboard_common_app/my_profile_change_password.html
{% block title %}
<h1><span>My Profile - Change Password</span></h1>
{% endblock %}
{% block content%}
    {% include 'core_dashboard_common_app/password_change.html' %}
{% endblock %}

core_dashboard_common_app/templates/core_dashboard_common_app/my_profile_edit.html
{% block title %}<h1><span>My Profile - Edit</span></h1>{% endblock %}

{% block content%}
Use the following form to edit your information.
<div>
<form action="{% url 'core_dashboard_profile_edit' %}" method="post">
 	{% csrf_token %}
    {{ data.form }}
    <div id="profile_error" style="font-weight: bold;">
    {{ data.action_result }}
    </div>
    <div class="mt-5 d-flex justify-content-end">
        <button type="button" class="btn btn-secondary {% if BOOTSTRAP_VERSION|first == "4" %}mr-1{% elif BOOTSTRAP_VERSION|first == "5" %}me-1{% endif %}" onclick="location.href='{% url 'core_dashboard_profile' %}'">
            <i class="fas fa-times"></i> Cancel
        </button>
        <button type="submit" class="btn btn-primary">
            <i class="fas fa-save"></i> Save changes
        </button>
    </div>
</form>
</div>
{% endblock %}

core_dashboard_common_app/templates/core_dashboard_common_app/password_change.html
{% load i18n %}
{% if data.password_change_required %}
    <p class='help'>{% trans "Your password has expired. Please change it using the form below." %}</p>
{% else %}
    <p class='help'>Use the following form to change your password.</p>
{% endif %}

{% if data.form.non_field_errors %}
<div class="alert alert-danger">
    {{ data.form.non_field_errors }}
</div>
{% endif %}
{% if data.form_error_message %}
<div class="alert alert-danger">
    <strong><i class="fas fa-exclamation-circle"></i>{{ data.form_error_message }}</strong>
    <ul class="bullet-list">
        {% for error in data.error_items %}
            <li class="text-danger">
                {{ error }}
            </li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<form method="post">
  {% csrf_token %}
  {{ data.form }}
    <div class="mt-2 d-flex justify-content-end">
      <button type="submit" class="btn btn-primary btn-lg margin-top">
        <i class="fas fa-save"></i> Save changes
      </button>
    </div>

</form>